# Local MongoDB for development
# Usage: docker-compose -f docker-compose.db.yml up -d
version: "3.8"

services:
    mongodb:
        image: mongo:7-jammy
        container_name: animalia-mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin123
            MONGO_INITDB_DATABASE: animalia
        volumes:
            - mongodb_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/animalia --quiet
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mongodb_data:
        driver: local
