version: "3.8"

services:
    animalia:
        image: animalia
        container_name: animalia
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        restart: unless-stopped

networks:
    default:
        external:
            name: nginx-proxy-manager_default
