version: "3.4"

services:
    animalia:
        image: animalia
        container_name: animalia
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 4001:3000
        volumes:
            - .:/app
        restart: unless-stopped

volumes:
    data:

networks:
    default:
        external:
            name: nginx-proxy-manager_default
